vim.opt.ignorecase            = true
vim.opt.smartcase             = true
vim.opt.showmatch             = true
vim.opt.shiftwidth            = 2
vim.opt.tabstop               = 2
vim.opt.softtabstop           = 2
vim.opt.smartindent           = true
vim.opt.clipboard             = 'unnamedplus'
vim.wo.cursorline             = true
vim.opt.expandtab             = true
vim.opt.number                = true
vim.opt.relativenumber        = true
vim.o.termguicolors           = true
vim.g.mapleader               = ' '
vim.opt.laststatus            = 3
vim.g['loaded_perl_provider'] = 0
